prompt_order = """
    $time $username $hostname $directory\
    $git_branch $git_commit $git_state $git_status $hg_branch $package\
    $crystal $dotnet $elixir $elm $erlang $golang $java $julia $nim\
    $nodejs $ocaml $php $purescript $python $ruby $rust $terraform $zig\
    $nix_shell $conda\
    $memory_usage $kubernetes $docker_context\
    $aws $env_var $custom $cmd_duration $line_break\
    $battery $jobs $character\
"""

[character]
success_symbol = "[➜](cyan)"
error_symbol = "[➜](red)"

[kubernetes]
symbol = "⛵ "
disabled = true

[aws]
style = "lightgreen"
symbol = "🅰  "

[gcloud]
disabled = true

[terraform]
format = "on [$version]($style)"

[time]
disabled = false
time_format = "%T"
style = "bold 10"
format = "[ ◷ [$time]($style) ]"

[username]
style_user = "bold cyan"
style_root = "bold red"

[python]
pyenv_version_name = true

[cmd_duration]
style = "red"

[git_branch]
style = "bold red"

[package]
style = "bold red"
display_private = true
