---
name: Nix Build

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            substituters = https://nrdxp.cachix.org https://nix-community.cachix.org
            trusted-public-keys = nrdxp.cachix.org-1:Fc5PSqY2Jm1TrWfm88l6cvGWwz3s93c6IOifQWnhNW4= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - name: Nix | Check Flake
        run: make check

      - name: Nix | Build flake for Nixbox
        run: |
          make DOTFILES=${GITHUB_WORKSPACE} HOST=nixbox build
